### ISSUE TITLE
Combining tilde sometimes displays as macron

### ISSUE THREAD

**Issue by Zabolekar** [notofonts/noto-fonts#1225]
For small font sizes, combining tilde U+0303 is displayed correctly over Cyrillic о U+043E, but not over Latin o U+006F.

The same problem appears when trying to display õ (U+00F5).

Here is a screenshot of о̃ õ with different Noto fonts and font sizes:

![notobug](https://user-images.githubusercontent.com/2109478/41524681-9325a39a-72de-11e8-815f-beb27bc79293.png)

Versions used:
NotoSerif-Regular.ttf and NotoSans-Regular.ttf:
2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)
NotoMono-Regular.ttf:
1.00

Tested on Xubuntu 18.04 with Mousepad, Libre Office Writer and GNOME Character Map.

**Comment by fitojb** [comment]
This is a FreeType bug and has been reported several times. Please search for duplicates before filing.

See https://savannah.nongnu.org/bugs/?23537

**Comment by simoncozens** [comment]
As this is not our bug, I'm closing here.
