### ISSUE TITLE
Create tags to match the specific version releases

### ISSUE THREAD

**Issue by Pomax** [notofonts/noto-fonts#1369]
There are currently no tags for releases, making it incredibly hard to get specific versioned fonts for tests that rely on them. For example, if a project has tests written against `Version 1.05 uh`, grabbing whatever is the latest release is almost guaranteed to break some tests not because the project has bad code, but because metadata in the font has changed since that version.

Could tags be created so that rather than trying to find commit hashes that yield specific versions of fonts, one can simply hit up https://github.com/googlei18n/noto-fonts/tree/version-1.05-uh?

**Comment by simoncozens** [comment]
This will now happen; the individual script repositories will create GitHub releases every time there is a new font. e.g. https://github.com/notofonts/test/releases
