### ISSUE TITLE
Versioned download URL

### ISSUE THREAD

**Issue by htruong** [notofonts/noto-fonts#1575]
Currently, (as far as I know) all fonts from the repository is not versioned, for example:

`https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArmenian-hinted.zip`

It would be very nice to have a versioned URL download link, because in many cases, download and integration tools need to check the integrity of the files downloaded by comparing to a SHA-??? hash.

A versioned URL could look like so:

`https://noto-website-2.storage.googleapis.com/pkgs/20190909/NotoSansArmenian-hinted.zip`

It also makes it much easier to archive, retrieve and refer to in the long term.

**Comment by htruong** [comment]
Sorry to bother, but I wonder if there is any update on this? 

I am writing a tool to automate downloading and installing Noto for a build system. For this tool to work, there has to be a versioned URL with a unchanging hash, or the tool will reject the download as corrupted whenever you update the fonts.

**Comment by simoncozens** [comment]
See also #1369; there is a new build process, and the individual script repositories will create GitHub releases every time there is a new font. e.g. https://github.com/notofonts/test/releases
