### ISSUE TITLE
Missing Korean Chancters in PDF

### ISSUE THREAD

**Issue by bhansali-mukesh** [notofonts/noto-fonts#1757]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Missing Korean Chancters in PDF
### Font 
  > NotoSansCJKjp-Regular.otf.
  > You can upload the problem font here unless it is a Chinese, Japanese or Korean font (these are large).

### Where the font came from, and when
  > For example:
  >   Site: https://www.google.com/get/noto/
  >   Date: 2020-03-03

### Font Version
  > * Version 1.004;PS 1.004;hotconv 1.0.82;makeotf.lib2.5.63406

### OS name and version
  > CentOS Linux release 7.7.1908 (Core)
Derived from Red Hat Enterprise Linux 7.7 (Source)

### Application name and version
  > Jasper Reports 6.8.1

### Issue
  > When Report is produced using this font for Korean Language and Format is PDF, Some Characters are missing in Report. In HTML it looks fine.
Tried with Diffrent Font and found that it is working perfectly fine with othe font.

  1. Any Jasper Report in PDF with This Font, Locale must be Korean 
  2. Works fine in HTML but Missing few characters in Korean PDF Report
  3. It should match HTML Report as it is working with other font.
  
### Character data
  > 통제청 추
[Noto Sans CJK JP Regular.pdf](https://github.com/googlefonts/noto-fonts/files/4687875/Noto.Sans.CJK.JP.Regular.pdf)

[Type Dodam M.pdf](https://github.com/googlefonts/noto-fonts/files/4687868/Type.Dodam.M.pdf)
![Type Dodam M](https://user-images.githubusercontent.com/3065035/83003446-f4d72600-a02b-11ea-8552-cc23e139d12e.PNG)

[noto.zip](https://github.com/googlefonts/noto-fonts/files/4687860/noto.zip)

![Noto Sans CJK JP Regular](https://user-images.githubusercontent.com/3065035/83003308-c22d2d80-a02b-11ea-86ca-8a6ead030711.PNG)

lease include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by bhansali-mukesh** [comment]
![Diff-Noto Sans CJK JP Regular](https://user-images.githubusercontent.com/3065035/83004931-da05b100-a02d-11ea-8283-585dc9833e90.png)

**Comment by punchcutter** [comment]
The PDF creation looks broken. When I try to open the PDFs you attached I get an error 

> Cannot extract the embedded font 'XTCOAU+NotoSansCJKjp-Bold-Identity-H'. Some characters may not display or print correctly.

Also, you should get the latest version of the fonts from https://github.com/googlefonts/noto-cjk/releases if you don't have them. If it works with another font then which font?

**Comment by udayjadhav** [comment]
@punchcutter  We are using the latest font only
I have attached pdf file and HTML snapshot as well, we are using Noto Sans CJK JP Regular font, i tried with your mentioned font as well.
you might be getting Cannot extract the embedded font 'XTCOAU+NotoSansCJKjp-Bold-Identity-H'. Some characters may not display or print correctly, because font may not be available in your classpath, you can try opening it in the 
[Noto Sans CJK JP Regular.pdf](https://github.com/googlefonts/noto-fonts/files/4762992/Noto.Sans.CJK.JP.Regular.pdf)
browser.
![Noto Sans CJK JP Regular](https://user-images.githubusercontent.com/7446328/84353317-8d4cd900-abdc-11ea-8359-6f965207f911.PNG)
[Type Dodam M.pdf](https://github.com/googlefonts/noto-fonts/files/4763004/Type.Dodam.M.pdf)
![Type Dodam M](https://user-images.githubusercontent.com/7446328/84353322-8faf3300-abdc-11ea-898c-f3f1646e4a8e.PNG)

**Comment by patchew** [comment]
I would also think that using `Noto Sans CJK KR` would be more appropriate for Korean than `Noto Sans CJK JP`.

[Apologies for any typos – typed with my thumbs and subject to the most amusing auto-correct (or not), i.e. typed on my iPhone]

**Comment by Harshad-Panmand** [comment]
> I would also think that using `Noto Sans CJK KR` would be more appropriate for Korean than `Noto Sans CJK JP`. [Apologies for any typos – typed with my thumbs and subject to the most amusing auto-correct (or not), i.e. typed on my iPhone]
> […](#)
> On Jun 10, 2020, at 23:41, udayjadhav ***@***.***> wrote: ﻿ @punchcutter We are using the latest font only I have attached pdf file and HTML snapshot as well, we are using Noto Sans CJK JP Regular font, i tried with your mentioned font as well. you might be getting Cannot extract the embedded font 'XTCOAU+NotoSansCJKjp-Bold-Identity-H'. Some characters may not display or print correctly, because font may not be available in your classpath, you can try opening it in the Noto Sans CJK JP Regular.pdf browser. Type Dodam M.pdf — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@patchew I have used 'Noto Sans CJK KR *' still, it's not working.

[CAPA 기록 보고서 V2 (1).pdf](https://github.com/googlefonts/noto-fonts/files/5040061/CAPA.V2.1.pdf)
![CAPA_HTML](https://user-images.githubusercontent.com/20993027/89623399-284af200-d8b2-11ea-8851-843c055ef79f.jpg)

**Comment by patchew** [comment]
> @patchew / @punchcutter I have used 'Noto Sans CJK KR *' still, it's not working. In below added pdf korean characters are missing (As previous).

@Harshad-Panmand , were you able to resolve this?
When trying to open your attached PDF, it seems that there's more to it than just using the NotoSans CJK-KR fonts:

<img width="444" alt="Acrobat_Pro_DC_and_CAPA_V2_1_pdf" src="https://user-images.githubusercontent.com/6853292/98879207-d1693180-2439-11eb-8632-ad0e66a0305c.png">

**Comment by simoncozens** [comment]
This seems very similar to #1678 (same error message). Closing in favour of that. I suspect it's broken PDF generation software, but anything we can do to debug would be good.
