### ISSUE TITLE
Current Noto Sans Scripts Coverage (Excepted CJK and Emoji)

### ISSUE THREAD

**Issue by ghost** [notofonts/noto-fonts#2071]
What scripts does Noto Sans actually covers (excepted CJK and Emoji)?
The last news I saw is quite old (December 2020 from Wikipedia), which says that Noto covers 150 out of 154 Unicode 13.0 scripts.

**Comment by twardoch** [comment]
This is the list of ISO script codes supported by the current dev branch of Noto: 

Adlm, Aghb, Ahom, Arab, Armi, Armn, Avst, Bali, Bamu, Bass, Batk, Beng, Bhks, Bopo, Brah, Brai, Bugi, Buhd, Cakm, Cans, Cari, Cham, Cher, Chrs, Copt, Cprt, Cyrl, Deva, Diak, Dogr, Dsrt, Dupl, Egyp, Elba, Elym, Ethi, Geor, Glag, Gong, Gonm, Goth, Gran, Grek, Gujr, Guru, Hang, Hani, Hano, Hatr, Hebr, Hira, Hluw, Hmng, Hmnp, Hung, Ital, Java, Kali, Kana, Khar, Khmr, Khoj, Kits, Knda, Kthi, Lana, Laoo, Latn, Lepc, Limb, Lina, Linb, Lisu, Lyci, Lydi, Mahj, Maka, Mand, Mani, Marc, Medf, Mend, Merc, Mero, Mlym, Modi, Mong, Mroo, Mtei, Mult, Mymr, Nand, Narb, Nbat, Newa, Nkoo, Nshu, Ogam, Olck, Orkh, Orya, Osge, Osma, Palm, Pauc, Perm, Phag, Phli, Phlp, Phnx, Plrd, Prti, Rjng, Rohg, Runr, Samr, Sarb, Saur, Sgnw, Shaw, Shrd, Sidd, Sind, Sinh, Sogd, Sogo, Sora, Soyo, Sund, Sylo, Syrc, Tagb, Takr, Tale, Talu, Taml, Tang, Tavt, Telu, Tfng, Tglg, Thaa, Thai, Tibt, Tirh, Ugar, Vaii, Wara, Wcho, Xpeo, Xsux, Yezi, Yiii, Zanb, Zinh

Noto supports 46,888 out of 49,418 non-ideographic characters included in Unicode (94.88%), and including the CJK ideographs 77,755 out of 143,860 characters (54.04%).

**Comment by Binary-Hazard** [comment]
That's a good considering the size of the Unicode standard.

**Comment by Binary-Hazard** [comment]
That's a good point considering the size of the Unicode standard.

**Comment by simoncozens** [comment]
Please see the Noto Overview at https://notofonts.github.io/overview/
