### ISSUE TITLE
Asterism (U+2042 ⁂)

### ISSUE THREAD

**Issue by john-cj** [notofonts/noto-fonts#2215]
Is there the U+2042 (⁂) in Noto Serif?

I can see it by checking the character map in LibreOffice, but I cannot see it when typing in https://fonts.google.com/noto/specimen/Noto+Serif?query=Noto

![image](https://user-images.githubusercontent.com/18004961/149489204-cf22f7b7-58cb-45ae-9ca9-4153fbfa282d.png)

**Comment by Mercury13** [comment]
Long ago I reported #2116, here they are.

**Comment by marekjez86** [comment]
Noto has it in the sources:
NotoSans-ItalicMM.glyphs:unicode = 2042;
NotoSans-MM.glyphs:unicode = 2042;
NotoSansMono-MM.glyphs:unicode = 2042;
NotoSerif-ItalicMM.glyphs:unicode = 2042;
NotoSerif-MM.glyphs:unicode = 2042;
NotoSerifDisplay-ItalicMM.glyphs:unicode = 2042;
this is fonts.google.com font serving issue

**Comment by simoncozens** [comment]
More and more bizarre - it's in the bold but not the regular in Noto Serif on Google Fonts, and in the SemiBold and bolder in Noto Sans!
<img width="164" alt="Screenshot 2022-06-27 at 11 12 34" src="https://user-images.githubusercontent.com/106728/175918377-0b2b3814-abf9-436f-b08a-80c0644c8094.png">

Although it *is* in all the weights of the fonts in the Google Fonts repository... 

The fonts are right; I think this is a GF bug, sending it over to them.

(Closing in favour of https://github.com/google/fonts/issues/4836)
