### ISSUE TITLE
unhinted/ttf/NotoSansCJK/NotoSansCJK-Regular.ttc is HTML, not a font

### ISSUE THREAD

**Issue by pnorman** [notofonts/noto-fonts#2391]
### Issue
The file [https://github.com/notofonts/noto-fonts/blob/main/unhinted/ttf/NotoSansCJK/NotoSansCJK-Regular.ttc](unhinted/ttf/NotoSansCJK/NotoSansCJK-Regular.ttc) in this repo is a HTML page, not a TTC file.

**Comment by simoncozens** [comment]
Thanks; that file shouldn't even be in here, as CJK is delivered separately.

**Comment by antonio-rojas** [comment]
Same for `NotoSerifCJK-Regular.ttc`
