### ISSUE TITLE
Single character display problem with Simplified Chinese font

### ISSUE THREAD

**Issue by myNameIsKosLin** [notofonts/noto-fonts#2394]
# Single character display problem with Simplified Chinese font

### Basic Information

font: ZCOOLXiaoWei-Regular.ttf 

(font for chinese-simplified)

download from fonts.google.com 

date：2022/8/1

Version 1.000

on newest macOS

### Problem

the character "回" can't be displayed correctly 

This is a font issue, not a single-case display issue. I have used the font on my blog and tried it on the preview interface of my website. The screenshot below is a preview in Google Fonts, where the word appears as a solid square. 

<img src="https://raw.githubusercontent.com/myNameIsKosLin/ForPictures/main/CleanShot%202022-08-06%20at%2011.28.50%402x.png" alt="CleanShot 2022-08-06 at 11.28.50@2x" style="zoom: 25%;" />

And normally it should look like this

![CleanShot 2022-08-06 at 13.20.05@2x](https://raw.githubusercontent.com/myNameIsKosLin/ForPictures/main/CleanShot%202022-08-06%20at%2013.20.05%402x.png)

**Comment by simoncozens** [comment]
There is a bug in this font, but Zcool Xaiowei  is not a Noto font; I have reported the issue as https://github.com/googlefonts/zcool-xiaowei/issues/4
