### ISSUE TITLE
The new bug reporter is broken

### ISSUE THREAD

**Issue by php4fan** [notofonts/noto-fonts#2397]
In readme.md it says:

> This repository is in the process of being migrated.
> (...)
> To report a bug in a Noto font, please visit https://notofonts.github.io/reporter.html

so I went there, and I get this:

![image](https://user-images.githubusercontent.com/13969584/183526072-16618e64-a974-40e6-b3b6-5e3ebaf80e61.png)

I select Noto Arimo, and I get this:

![image](https://user-images.githubusercontent.com/13969584/183526142-af3b3615-19b5-4134-b130-d672da1cd59b.png)

**Comment by simoncozens** [comment]
Ah. Yes. “onchange” won’t do anything if the value doesn’t actually change… I’ll sort it.
