### ISSUE TITLE
Noto Color Emoji - inconsistent embedding restriction 

### ISSUE THREAD

**Issue by cc-cake** [notofonts/noto-fonts#2408]
### Font
  > NotoColorEmoji-Regular.ttf
### Where the font came from, and when
  >   https://fonts.google.com/noto/specimen/Noto+Color+Emoji?noto.query=emoji
  >   Date: 12/23/22
### Font Version
  > Version 2.038;GOOG;noto-emoji:20220906:4b1c5bfb0d5b1f5c69aa321d5b6e70656ead1d30
### Application name and version
  > FontBook
### Issue
 > I am not sure if this is intentional, I am guessing not, so creating this report. In the Usage data embedded in the font file it states the following restriction regarding embedding: <br>
> "Preview and print embedding. This font may be embedded in documents and temporarily loaded on the remote system. Documents containing this font must be opened “read-only;” no edits can be applied to the document." <br>
> This isn't consistent with other Noto family fonts, such as with "Noto Emoji" and "Noto Sans" it states:<br>
>"No embedding restrictions."

**Comment by simoncozens** [comment]
Thanks for the report. This appears to be an issue with the fonts.google.com server, as the font file before being subsetted by the server has the correct permissions. I'll follow this up with the engineering people.

**Comment by simoncozens** [comment]
I understand how this has happened; filed as https://github.com/google/fonts/issues/5729
