### ISSUE TITLE
Issue with noto fonts JP  "Ó" is different

### ISSUE THREAD

**Issue by pineshpatelgenero** [notofonts/noto-fonts#2411]
Facing an issue with displaying the  "Ó"  on Noto sens JP fonts, from google font CDN we face this problem even on google URLs also.
Please add support for that character.
Please check the below image for more information
![image](https://user-images.githubusercontent.com/101395147/213140123-10a73423-b66c-4031-9217-2e26c0630b98.png)
Thank you!!

**Comment by simoncozens** [comment]
Confirmed on Google Chrome. (The rendering is correct on Safari.) This looks to be a bug with the Google Fonts API and subsetter, not with Noto, as the glyph is correct in the font. I can't transfer this issue to google/fonts but will close here and open an issue over there.
