### ISSUE TITLE
Noto Color Emoji seems to include a space character (U+0020)

### ISSUE THREAD

**Issue by Alexendoo** [notofonts/noto-fonts#753]
However it seems to mess up the display somewhat in firefox mobile and chrome desktop, [this pen for example](http://codepen.io/Alexendoo/pen/ozokvx) displays as:

![image](https://cloud.githubusercontent.com/assets/1830331/19058294/efc936c6-89cd-11e6-8abf-c95ef16a54b2.png)

I don't know if this is an issue with the software or the font but it does occur on multiple browsers + OSes

**Comment by dougfelt** [comment]
I get a space between Hello and World at that link (Chrome on Ubuntu).  NotoColorEmoji's space is 2550 design units, the same as most characters in the font.  I'm not sure why it would not be showing with that width, if simple character-based fallback is being used.

**Comment by TidharC** [comment]
I retested the pen above with a few browsers: Firefox (including the beta version) on Android is the only one where the space is missing.  All other browsers I tried show the space:

MacOS: Chrome, Firefox, Safari
Android: Chrome, Opera, Opera Mini
iOS: Chrome, Firefox, Safari

 @Alexendoo, what is your desktop OS?

**Comment by Alexendoo** [comment]
Xubuntu, both chrome and chromium. Inspector shows it's displaying 10 glyphs from Liberation Sans and 1 from Noto Color Emoji

**Comment by KatMomoi** [comment]
Android Firefox seems to ignore space within <p> </p>. Can you try something like <span></span> and see what happens? 
Also would Android Firefox behave the same if the font-family simply listed "sans-serif" without "Noto Color Emoji"?

**Comment by KatMomoi** [comment]
I meant to say Android Firefox seems to ignore a space within "p" element.  Can you try "span" element instead?

**Comment by KatMomoi** [comment]
What I am hinting at is that this could be a browser bug.

**Comment by Alexendoo** [comment]
It's not present when it's just sans-serif, only when the glyph is rendered as Noto Color Emoji

Same happens with other elements

**Comment by dougfelt** [comment]
I don't know what to do with this bug.  Noto Color Emoji does have a space character, all Noto fonts do.  The space character is the width of a standard emoji character.  Many browsers/environments seem to handle this ok, they do at least render a space.  The fact that firefox/xubuntu fails to render it entirely seems like a bug between the browser/os.  It doesn't seem like our problem.

**Comment by fserb** [comment]
Chrome/Linux also seems to skip spaces when using Noto Color Emoji. Help?

**Comment by dougfelt** [comment]
Well, it works for me using Chrome 62.0.3202.62 on ubuntu.  What are you doing?
![emoji_with_space](https://user-images.githubusercontent.com/9939212/32027905-97f474d4-b9a0-11e7-9d30-03c921186670.png)

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Emoji space</title>
    <style>@font-face {
      font-family:"Emoji"; src:local("Noto Color Emoji"), url("./fonts/NotoColorEmoji.ttf");
      }
      .efont {font-family:"Emoji"; font-size:32pt; }
    </style>
  </head>
  <body>
    <p class="efont">&#x1f600; &#x1f62a; &#x1f615;</p>
  </body>
</html>```

**Comment by simoncozens** [comment]
This seems to be fixed on current Firefox. If it is still a problem, I'm fairly sure it is a Firefox-specific one, so please reopen at https://bugzilla.mozilla.org
