### ISSUE TITLE
Tofu as tested on http://www.alanwood.net/unicode/

### ISSUE THREAD

**Issue by guilt** [notofonts/noto-fonts#775]
Hi,

I decided to see what ranges were missing, and I was able to come up with a decent list. This was seen on macOS Sierra with Firefox 49.0. I downloaded the Noto-unhinted.zip from Google Noto as of today (12:00 PM UTC)

Since I did not want to create multiple tickets for it, I'm posting the ranges with names (as identified by each range's sample image) to test against.

Once the font is installed, you can test them for tofus on that web site.

<img width="628" alt="01-greek one quarter" src="https://cloud.githubusercontent.com/assets/195178/19477129/63271bd2-955a-11e6-8239-1dc06eb21277.png">
<img width="551" alt="02-greek symbol" src="https://cloud.githubusercontent.com/assets/195178/19477131/63294718-955a-11e6-8e4f-7cc1655f6009.png">
<img width="618" alt="03-coptic epact" src="https://cloud.githubusercontent.com/assets/195178/19477130/63286f8c-955a-11e6-99e3-fce04282a27a.png">
<img width="564" alt="04-italian letter" src="https://cloud.githubusercontent.com/assets/195178/19477133/632f1b98-955a-11e6-9413-8eed63c9ad4e.png">
<img width="668" alt="05-meroitic hieroglyphic" src="https://cloud.githubusercontent.com/assets/195178/19477134/633003aa-955a-11e6-9fe4-980945a5df70.png">
<img width="628" alt="06-meroitic cursive" src="https://cloud.githubusercontent.com/assets/195178/19477132/632b4f86-955a-11e6-80f0-39bcc32e481c.png">
<img width="523" alt="07-rumi digit" src="https://cloud.githubusercontent.com/assets/195178/19477135/6357d312-955a-11e6-9a55-18a826a5418a.png">
<img width="580" alt="08-brahmi number joiner" src="https://cloud.githubusercontent.com/assets/195178/19477136/635a7d10-955a-11e6-8fa2-7344252fbce4.png">
<img width="595" alt="09-sora sompeng letter" src="https://cloud.githubusercontent.com/assets/195178/19477137/635ac0b8-955a-11e6-9cd4-638df7038d3c.png">
<img width="807" alt="10-chakma sign" src="https://cloud.githubusercontent.com/assets/195178/19477138/635d9482-955a-11e6-94f8-f0c8cdb0c1fd.png">
<img width="798" alt="11-sharada sign" src="https://cloud.githubusercontent.com/assets/195178/19477140/636908c6-955a-11e6-8fe9-8c66e5a7b7e3.png">
<img width="543" alt="12-takri letter" src="https://cloud.githubusercontent.com/assets/195178/19477139/636318c6-955a-11e6-9c74-ae83470a9b31.png">
<img width="659" alt="13-cuneiform sign" src="https://cloud.githubusercontent.com/assets/195178/19477142/6392f0dc-955a-11e6-8d00-13f5cfce4c17.png">
<img width="868" alt="14-cuneiform numeric sign" src="https://cloud.githubusercontent.com/assets/195178/19477145/639a4b3e-955a-11e6-92da-09371dfccf2a.png">
<img width="525" alt="15-miao letter" src="https://cloud.githubusercontent.com/assets/195178/19477143/6394f300-955a-11e6-9ba3-d7074e83ffb7.png">
<img width="615" alt="16-katakana letter archaic" src="https://cloud.githubusercontent.com/assets/195178/19477144/6395fe62-955a-11e6-9b76-83d9b1eb4afa.png">
<img width="658" alt="17-arabic mathematical" src="https://cloud.githubusercontent.com/assets/195178/19477146/639a8f86-955a-11e6-8009-3d4ade9bf5e3.png">
<img width="584" alt="18-playing card" src="https://cloud.githubusercontent.com/assets/195178/19477147/639db06c-955a-11e6-8ca3-128ec0e2f4f5.png">
<img width="646" alt="19-transport and map symbols" src="https://cloud.githubusercontent.com/assets/195178/19477149/63c8aa42-955a-11e6-9958-1d0a853047cb.png">
<img width="667" alt="20-cjk ideograph extension b" src="https://cloud.githubusercontent.com/assets/195178/19477150/63cb2a2e-955a-11e6-8cd0-efffbfd0ac64.png">
<img width="632" alt="21-cjk ideograph extension c" src="https://cloud.githubusercontent.com/assets/195178/19477148/63c7783e-955a-11e6-9eba-859f1c05a667.png">
<img width="629" alt="22-cjk unified ideograph" src="https://cloud.githubusercontent.com/assets/195178/19477151/63cba832-955a-11e6-83a5-afe1838d8d70.png">
<img width="677" alt="23-cjk compatibility ideograph" src="https://cloud.githubusercontent.com/assets/195178/19477152/63ce1bbc-955a-11e6-916f-693e181cf43f.png">

Ranges to verify:

01-GREEK ONE QUARTER
02-GREEK SYMBOL
03-COPTIC EPACT
04-ITALIAN LETTER
05-MEROITIC HIEROGLYPHIC
06-MEROITIC CURSIVE
07-RUMI DIGIT
08-BRAHMI NUMBER JOINER
09-SORA SOMPENG LETTER
10-CHAKMA SIGN
11-SHARADA SIGN
12-TAKRI LETTER
13-CUNEIFORM SIGN
14-CUNEIFORM NUMERIC SIGN
15-MIAO LETTER
16-KATAKANA LETTER ARCHAIC
17-ARABIC MATHEMATICAL
18-PLAYING CARD
19-TRANSPORT AND MAP SYMBOLS
20-CJK IDEOGRAPH EXTENSION B
21-CJK IDEOGRAPH EXTENSION C
22-CJK UNIFIED IDEOGRAPH
23-CJK COMPATIBILITY IDEOGRAPH

**Comment by marekjez86** [comment]
@guilt : Karthik, thank you for your feedback. https://www.google.com/get/noto/ contains the fonts released so far. Many other fonts are still in progress and many fonts haven't started yet. I'll keep this bug open assigned to me and I'll update it as we progress.

**Comment by dougfelt** [comment]
Thanks.  We're aware that the current iteration of Noto doesn't cover all Unicode 6 codepoints, and we're working to remedy this.  The current target is Unicode 9 and the current list is on github at googlei18n/nototools/nototools/noto_cmap_phase3.xml.  It will take a year or two to fill everything out.

What would help us the most is information specific to a language and script that illustrates what combining forms we are missing or where existing ones are incorrect.

**Comment by cheuk879** [comment]
NotoSansMiao Version 2.001 (Revision 2.00101, last modified 2020-12-25) has correct glyphs for 16F00..16F01:
![plrd-noto-pa+ba](https://user-images.githubusercontent.com/10625598/104773109-bf558900-5731-11eb-8a1c-c4bb89f6afaf.png)

**Comment by marekjez86** [comment]
@cheuk879 : thank you

**Comment by simoncozens** [comment]
At this stage, the only ones missing are the Kana Supplement block, CJK extension blocks B and C, and the CJK compatibility ideographics. (Notice a theme?) You can see the current coverage of the Noto project at https://notofonts.github.io/overview/

We will work on getting the CJK blocks filled out.
