### ISSUE TITLE
NotoColorEmoji.ttf

### ISSUE THREAD

**Issue by lgd8069465** [notofonts/noto-fonts#890]
![image](https://cloud.githubusercontent.com/assets/7867042/24687174/d36ee5c2-19ea-11e7-8ce4-cd57d8575ec2.png)

next?

**Comment by zjusbo** [comment]
Hi lgd8069465,

Thanks for reporting this bug. Please provide more detailed info before we can identify the problem. It will save both your and our time. For example,

1. What's you OS? Windows 7, Windows 8?
2. What's your language settings? Is it zn-ch? Or say, is it simplified Chinese? 
3. What's the full path you used when installing this font? From my experience, some wired errors may occur if the path contains non-ascii characters, say Chinese characters. 
4. Where did you get the font, is it from this Noto-font repo? Or is it from https://github.com/googlei18n/noto-emoji/blob/master/fonts/NotoColorEmoji.ttf ? If it's from the later one, probably the noto-emoji is a better place to file this bug.
5. Any other info you think might be helpful.

Thanks.

**Comment by dougfelt** [comment]
Noto Color Emoji will not work on Windows versions before Windows 10
Anniversary Update.

**Comment by lgd8069465** [comment]
@zjusbo Windows 7,Simplified Chinese,From https://www.google.com/get/noto/ 
@dougfelt All right,thanks.

**Comment by Kanjilearner817** [comment]
I'm running Windows 10 post-Anniversary Update and it doesn't work for me.

**Comment by KrasnayaPloshchad** [comment]
This bug have already reported.
https://github.com/googlei18n/noto-emoji/issues/43
