### ISSUE TITLE
Unable to merge Armenian and Hebrew with other fonts

### ISSUE THREAD

**Issue by esidegallery** [notofonts/noto-fonts#908]
### Title 
Attempting to merge Armenian or Hebrew fonts with any other Noto font using merge_fonts.py results in an error.

### Font 
Both unhinted and hinted versions of:
* NotoSansArmenian-Bold.ttf
* NotoSansArmenian-Regular.ttf
* NotoSerifArmenian-Bold.ttf
* NotoSerifArmenian-Regular.ttf
* NotoSansHebrew-Bold.ttf
* NotoSansHebrew-Regular.ttf
* NotoSerifHebrew-Bold.ttf
* NotoSerifHebrew-Regular.ttf

### Where the font came from, and when
GitHub repo, 27/04/17

### OS name and version
Font is not installed

### Issue
The following is an example font list in the merge_fonts.py script:
`files = ['NotoSans-Regular.ttf', 'NotoSansArmenian-Regular.ttf']`

Then, running the command `merge_fonts.py -d /Users/timwjohn/Desktop/noto-fonts-master/unhinted -o NotoSansArmenian-Regular.ttf` results in:

```
Merging 2 Fonts...
Traceback (most recent call last):
  File "/usr/local/bin/merge_fonts.py", line 8, in <module>
    execfile(__file__)
  File "/Users/timwjohn/Desktop/nototools-master/nototools/merge_fonts.py", line 118, in <module>
    main()
  File "/Users/timwjohn/Desktop/nototools-master/nototools/merge_fonts.py", line 105, in main
    font = merger.merge(valid_files)
  File "build/bdist.macosx-10.11-intel/egg/fontTools/merge.py", line 811, in merge
  File "build/bdist.macosx-10.11-intel/egg/fontTools/merge.py", line 159, in merge
  File "build/bdist.macosx-10.11-intel/egg/fontTools/merge.py", line 856, in mergeObjects
  File "build/bdist.macosx-10.11-intel/egg/fontTools/merge.py", line 48, in equal
AssertionError: Expected all items to be equal: [2048, 1000]
```

The result is the same with the Hebrew fonts.

Using a third party application such as FontForge yields sizing issues whereby Armenian and Hebrew are approximately half the size of the others. The two fonts will merge with each other however.

**Comment by dougfelt** [comment]
This problem will continue to worsen as we promote more phase 3 fonts, whose outlines are 1000 upem, while retaining mostly phase 2 fonts whose outlines are at 2048 upem (until the balance shifts and it eventually starts to get better).  Some font outlines will get rescaled and they will change slightly as a result.  @brawer, what do you recommend?

**Comment by marekjez86** [comment]
@esidegallery : get your fonts from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans

the fonts there should have consistent, 1000 upem outlines. This bug will be re-created in nototools if re-scaling of a font before merging is easy or closed as a feature of merge_fonts.py . @dougfelt : what do you think?

**Comment by abumoallim** [comment]
I had a same problem while combining NotoSans-Gujarati . is there any 1000 upem outlines for NotoSans-Gujarati.

**Comment by simoncozens** [comment]
All the fonts in https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf should now have 1000 upem outlines (I just checked Armenian, Hebrew and GujaratI), so you should be able to merge them.
